name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v2

      # Upload
      - name: Upload
        uses: ./
        with:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PROJECT_NAME: 'pr-docs-site-action'
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_LOCATION: ${{ secrets.PULUMI_LOCATION }}
